# Engine settings
clearcolorbuffer	1
clearcolor	0.0000000 0.0000000 0.0000000 0.0000000
ambient	1.0000000 1.0000000 1.0000000 1.0000000
fog	0
fogcolor	0.0000000 0.0000000 0.0000000 0.0000000
fogmode	exp
fogstart	100.0000000
fogend	500.0000000
fogdensity	1.0000000


# Object creation

new sivicPackage ground_horsering
new sivicPackage sky_bluedream
new sivicPackage sun
new sivicPackage ego_car
new sivicPackage dashcam
new sivicPackage radar
new mgPositionable col_det_1
new mgPositionable col_det_2
new mgPositionable col_det_3
new mgPositionable col_det_4
new mgPositionable col_det_5
new mgPositionable col_det_6
new sivicPackage dummy
new sivicPackage ego_car_obs
new sivicObjectObserver ped_obs
new sivicEvent col_event_1
new sivicEvent col_event_2
new sivicEvent col_event_3
new sivicEvent col_event_4
new sivicEvent col_event_5
new sivicEvent col_event_6


# Object configuration

# Object _DefaultRenderer with type mgAccurateRenderer
_DefaultRenderer.SetDisabled	0
_DefaultRenderer.SetHidden	1
_DefaultRenderer.SetPersistent	1
_DefaultRenderer.SetWireframe 0
_DefaultRenderer.SetNoTextures 0
_DefaultRenderer.SetClampVertexColor 0
_DefaultRenderer.SetClampFragmentColor 0

# Object editor with type sivicPackage
editor.SetDisabled	0
editor.SetHidden	1
editor.SetPersistent	1
editor.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object editor/cam with type sivicCamera
editor/cam.SetPeriod 0.0400000
editor/cam.SetOMGDDSEnabled false
editor/cam.SetFileName cam
editor/cam.SetExtension .cap
editor/cam.Off 
editor/cam.SetRecordEnabled false
editor/cam.SetExportFormat tsv
editor/cam.SetDisabled	0
editor/cam.SetPersistent	1
editor/cam.SetLocalPosition	281.8527527 305.6180420 4.7809229
editor/cam.SetLocalRotation	15.1601286 -58.3057175 -140.7626495
#editor/cam.SetLocalRotationAngles	44.9999428 0.0000043 -150.8503876
editor/cam.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/cam.SetFrustum	-0.1369319 0.1369319 -0.0767327 0.0767327 0.1000000 5000.0000000
editor/cam.SetRenderSize 1292 724
editor/cam.SetRenderer editor/ren
editor/cam.SetCaptureFileName MGEngine
editor/cam.SetClearColorBufferRegion 1
editor/cam.SetColorFormat rgb8
editor/cam.SetDepthFormat DEPTH_24
editor/cam.SetMultiSamples 4
editor/cam.SetCorrectDistortion 1
editor/cam.SetEnableIntegration 0
editor/cam.SetExposureTime 0.0400000
editor/cam.SetExposureSampling 0.0050000
editor/cam.SetMatrixSize 2.6666000 2.0000000
editor/cam.SetFocalLength 1.3032253
editor/cam.SetZNear 0.1000000
editor/cam.SetZFar 5000.0000000
editor/cam.SetCollectDepthImage off
editor/cam.SetDepthImageRange 1000
editor/cam.SetDepthImageResolution 1
editor/cam.SetImageType RGB24
editor/cam.SetNbEffectiveBits 8
editor/cam.SetRecordFormat bmp
editor/cam.SetPNGCompression png_1
editor/cam.SetModeCorrection off
editor/cam.SetCollectLabelImage 0
editor/cam.SetOccludeLabels 1

# Object editor/view with type sivicCameraViewport
editor/view.SetDisabled	0
editor/view.SetPersistent	1
editor/view.SetAutoResize 1
editor/view.SetViewport 0.0000000% 0.0000000% 100.0000000% 100.0000000%
editor/view.SetCamera editor/cam
editor/view.SetColorMask 1 1 1
editor/view.SetForceCameraResize 1
editor/view.SetMinDepthRange 0.0000000
editor/view.SetMaxDepthRange 100.0000000
editor/view.SetLookupTexture 

# Object editor/ren with type sivicEditorRenderer
editor/ren.SetDisabled	0
editor/ren.SetPersistent	1
editor/ren.SetWireframe 0
editor/ren.SetNoTextures 0
editor/ren.SetClampVertexColor 0
editor/ren.SetClampFragmentColor 0
editor/ren.SetShowGrid 1
editor/ren.SetGridMesh checker
editor/ren.SetShowAxes 1
editor/ren.SetAxesMesh repere
editor/ren.SetHighlight 1
editor/ren.SetHighlightColor 1.0000000 0.3000000 0.0000000 

# Object editor/cont with type mgPositionController
editor/cont.SetDisabled	0
editor/cont.SetPersistent	1
editor/cont.AttachTo editor/cam
editor/cont.SetXPosController	x_trans3
editor/cont.SetYPosController	y_trans3
editor/cont.SetZPosController	z_trans3
editor/cont.SetXRotController	x_rot3
editor/cont.SetYRotController	y_rot3
editor/cont.SetZRotController	z_rot3
editor/cont.SetTranslationSpeed	10.0000000
editor/cont.SetRotationSpeed	3.1415899
editor/cont.SetRealTime	on
editor/cont.SetMode Fly

# Object editor/tt with type mgTrackTo
editor/tt.SetDisabled	0
editor/tt.SetPersistent	1
editor/tt.ApplyTo editor/cam

# Object editor/_RendererPlugin_sivicBeaconReceiverDisplay with type sivicBeaconReceiverDisplay
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetDisabled	0
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetPersistent	1
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetShowAll 0
editor/_RendererPlugin_sivicBeaconReceiverDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicBeaconTransmitterDisplay with type sivicBeaconTransmitterDisplay
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetDisabled	0
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetPersistent	1
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetShowAll 0
editor/_RendererPlugin_sivicBeaconTransmitterDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicCameraDisplay with type sivicCameraDisplay
editor/_RendererPlugin_sivicCameraDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCameraDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCameraDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCameraDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCameraDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCameraDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCameraDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCameraDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCameraDisplay.SetDoNotRender	0

# Object editor/_RendererPlugin_sivicCarDisplay with type sivicCarDisplay
editor/_RendererPlugin_sivicCarDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCarDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCarDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCarDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCarDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCarDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCarDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCarDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCarDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicCarDisplay.SetShowTrackLeft 1
editor/_RendererPlugin_sivicCarDisplay.SetShowTrackCenter 1
editor/_RendererPlugin_sivicCarDisplay.SetShowTrackRight 1
editor/_RendererPlugin_sivicCarDisplay.SetShowPath 1
editor/_RendererPlugin_sivicCarDisplay.SetZShift 0.1000000
editor/_RendererPlugin_sivicCarDisplay.SetColorPath 0 255 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkCenter 0 255 255 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkLeft 0 0 255 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkRight 255 0 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorPathPoints 155 0 100 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkCenterPoints 255 0 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkLeftPoints 255 255 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetColorTrkRightPoints 255 255 0 255 
editor/_RendererPlugin_sivicCarDisplay.SetPointSize 1.0000000
editor/_RendererPlugin_sivicCarDisplay.SetShowMeanTurningRadiusFront 0
editor/_RendererPlugin_sivicCarDisplay.SetShowTurningFrontDeadZone 0
editor/_RendererPlugin_sivicCarDisplay.SetShowCollisionRaytrace 0

# Object editor/_RendererPlugin_sivicCommunicationDisplay with type sivicCommunicationDisplay
editor/_RendererPlugin_sivicCommunicationDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCommunicationDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCommunicationDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCommunicationDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCommunicationDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCommunicationDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCommunicationDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCommunicationDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCommunicationDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicCommunicationDisplay.SetShowAll 0
editor/_RendererPlugin_sivicCommunicationDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicCompassDisplay with type sivicCompassDisplay
editor/_RendererPlugin_sivicCompassDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCompassDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCompassDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCompassDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCompassDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCompassDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCompassDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCompassDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCompassDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicCompassDisplay.SetWireframe 1
editor/_RendererPlugin_sivicCompassDisplay.SetShowWind 1

# Object editor/_RendererPlugin_sivicCompassRoseDisplay with type sivicCompassRoseDisplay
editor/_RendererPlugin_sivicCompassRoseDisplay.SetDisabled	0
editor/_RendererPlugin_sivicCompassRoseDisplay.SetPersistent	1
editor/_RendererPlugin_sivicCompassRoseDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicCompassRoseDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicCompassRoseDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicCompassRoseDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicCompassRoseDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicCompassRoseDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicCompassRoseDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicCompassRoseDisplay.SetWireframe 0
editor/_RendererPlugin_sivicCompassRoseDisplay.SetShowWind 1
editor/_RendererPlugin_sivicCompassRoseDisplay.SetCompassPoint 8

# Object editor/_RendererPlugin_sivicDistanceObserverDisplay with type sivicDistanceObserverDisplay
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetDisabled	0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetPersistent	1
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetShowAll 0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetWireframe 1
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetShowObjectIndicator 0
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetShowMeasurePoint 1
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetColor 0.0000000 0.0000000 1.0000000
editor/_RendererPlugin_sivicDistanceObserverDisplay.SetLineWidth 5.0000000

# Object editor/_RendererPlugin_sivicEventDisplay with type sivicEventDisplay
editor/_RendererPlugin_sivicEventDisplay.SetDisabled	0
editor/_RendererPlugin_sivicEventDisplay.SetPersistent	1
editor/_RendererPlugin_sivicEventDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicEventDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicEventDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicEventDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicEventDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicEventDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicEventDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicEventDisplay.SetShowAll 0
editor/_RendererPlugin_sivicEventDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay with type sivicExternalTrajectoryReaderDisplay
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetDisabled	0
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPersistent	1
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPrecision 8
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPathColor 1.0000000 0.3300000 0.5000000 1.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPointsColor 0.0000000 0.5000000 0.8000000 1.0000000
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetShowPath 1
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetShowPoints 1
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetShowOrientation 1
editor/_RendererPlugin_sivicExternalTrajectoryReaderDisplay.SetPointSize 0.0800000

# Object editor/_RendererPlugin_sivicGPSDisplay with type sivicGPSDisplay
editor/_RendererPlugin_sivicGPSDisplay.SetDisabled	0
editor/_RendererPlugin_sivicGPSDisplay.SetPersistent	1
editor/_RendererPlugin_sivicGPSDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicGPSDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicGPSDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicGPSDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicGPSDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicGPSDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicGPSDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicGPSDisplay.SetShowAll 0
editor/_RendererPlugin_sivicGPSDisplay.SetWireframe 1

# Object editor/_RendererPlugin_sivicHumanDisplay with type sivicHumanDisplay
editor/_RendererPlugin_sivicHumanDisplay.SetDisabled	0
editor/_RendererPlugin_sivicHumanDisplay.SetPersistent	1
editor/_RendererPlugin_sivicHumanDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicHumanDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicHumanDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicHumanDisplay.SetShowTrackLeft 1
editor/_RendererPlugin_sivicHumanDisplay.SetShowTrackCenter 1
editor/_RendererPlugin_sivicHumanDisplay.SetShowTrackRight 1
editor/_RendererPlugin_sivicHumanDisplay.SetShowPath 1
editor/_RendererPlugin_sivicHumanDisplay.SetZShift 0.1000000
editor/_RendererPlugin_sivicHumanDisplay.SetColorPath 0 255 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkCenter 0 255 255 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkLeft 0 0 255 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkRight 255 0 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorPathPoints 155 0 100 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkCenterPoints 255 0 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkLeftPoints 255 255 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetColorTrkRightPoints 255 255 0 255 
editor/_RendererPlugin_sivicHumanDisplay.SetPointSize 1.0000000
editor/_RendererPlugin_sivicHumanDisplay.SetShowWalkingZone 0

# Object editor/_RendererPlugin_sivicInclinometerDisplay with type sivicInclinometerDisplay
editor/_RendererPlugin_sivicInclinometerDisplay.SetDisabled	0
editor/_RendererPlugin_sivicInclinometerDisplay.SetPersistent	1
editor/_RendererPlugin_sivicInclinometerDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicInclinometerDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicInclinometerDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicInclinometerDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicInclinometerDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicInclinometerDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicInclinometerDisplay.SetDoNotRender	0

# Object editor/_RendererPlugin_sivicLightSourceDisplay with type sivicLightSourceDisplay
editor/_RendererPlugin_sivicLightSourceDisplay.SetDisabled	0
editor/_RendererPlugin_sivicLightSourceDisplay.SetPersistent	1
editor/_RendererPlugin_sivicLightSourceDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicLightSourceDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicLightSourceDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicLightSourceDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicLightSourceDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicLightSourceDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicLightSourceDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicLightSourceDisplay.SetShowAll 0
editor/_RendererPlugin_sivicLightSourceDisplay.SetWireframe 0

# Object editor/_RendererPlugin_sivicRadarHUD with type sivicRadarHUD
editor/_RendererPlugin_sivicRadarHUD.SetDisabled	0
editor/_RendererPlugin_sivicRadarHUD.SetPersistent	1
editor/_RendererPlugin_sivicRadarHUD.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicRadarHUD.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicRadarHUD.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicRadarHUD.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicRadarHUD.SetCastShadows	0
editor/_RendererPlugin_sivicRadarHUD.SetRenderOrder	5.0000000
editor/_RendererPlugin_sivicRadarHUD.SetDoNotRender	0
editor/_RendererPlugin_sivicRadarHUD.SetLobePlot 1
editor/_RendererPlugin_sivicRadarHUD.SetLogDisplay 1
editor/_RendererPlugin_sivicRadarHUD.SetDisplayResolution 1.0000000

# Object editor/_RendererPlugin_sivicRadarSimpleDisplay with type sivicRadarSimpleDisplay
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetDisabled	0
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetPersistent	1
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicRadarSimpleDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicRadarSimpleDisplay.SetDoNotRender	0

# Object editor/_RendererPlugin_sivicRangefinderDisplay with type sivicRangefinderDisplay
editor/_RendererPlugin_sivicRangefinderDisplay.SetDisabled	0
editor/_RendererPlugin_sivicRangefinderDisplay.SetPersistent	1
editor/_RendererPlugin_sivicRangefinderDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicRangefinderDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicRangefinderDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicRangefinderDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicRangefinderDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicRangefinderDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicRangefinderDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicRangefinderDisplay.SetShowAll 1
editor/_RendererPlugin_sivicRangefinderDisplay.SetWireframe 0

# Object editor/_RendererPlugin_sivicRCSDisplay with type sivicRCSDisplay
editor/_RendererPlugin_sivicRCSDisplay.SetDisabled	0
editor/_RendererPlugin_sivicRCSDisplay.SetPersistent	1
editor/_RendererPlugin_sivicRCSDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicRCSDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicRCSDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicRCSDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicRCSDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicRCSDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicRCSDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicRCSDisplay.SetShowAll 0
editor/_RendererPlugin_sivicRCSDisplay.SetWireframe 0

# Object editor/_RendererPlugin_sivicTrajectoryDisplay with type sivicTrajectoryDisplay
editor/_RendererPlugin_sivicTrajectoryDisplay.SetDisabled	0
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPersistent	1
editor/_RendererPlugin_sivicTrajectoryDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicTrajectoryDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicTrajectoryDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetDoNotRender	0
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPrecision 8
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPathColor 0.2000000 0.6000000 0.5000000 1.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPointsColor 0.0000000 0.5000000 0.8000000 1.0000000
editor/_RendererPlugin_sivicTrajectoryDisplay.SetShowPath 1
editor/_RendererPlugin_sivicTrajectoryDisplay.SetShowPoints 1
editor/_RendererPlugin_sivicTrajectoryDisplay.SetShowOrientation 1
editor/_RendererPlugin_sivicTrajectoryDisplay.SetPointSize 0.0800000

# Object editor/_RendererPlugin_sivicUltrasonicSensorDisplay with type sivicUltrasonicSensorDisplay
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetDisabled	0
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetPersistent	1
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetLocalPosition	0.0000000 0.0000000 0.0000000
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetLocalRotation	0.0000000 0.0000000 0.0000000
#editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetLocalScale	1.0000000 1.0000000 1.0000000
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetCastShadows	0
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetRenderOrder	4.0000000
editor/_RendererPlugin_sivicUltrasonicSensorDisplay.SetDoNotRender	0

# Object ground_horsering with type sivicPackage
ground_horsering.SetDisabled	0
ground_horsering.SetLocalPosition	0.0000000 0.0000000 0.0000000
ground_horsering.SetLocalRotation	0.0000000 0.0000000 0.0000000
#ground_horsering.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
ground_horsering.SetLocalScale	1.0000000 1.0000000 1.0000000
ground_horsering.SetPackageData	Ground_horsering.zip

# Object ground_horsering/horsering_ground with type sivicBSPActor
ground_horsering/horsering_ground.AddProperty	BaseSurfaceGrip	float	1
ground_horsering/horsering_ground.AddProperty	ColorLabel	mgColor	128 128 128 255
ground_horsering/horsering_ground.AddProperty	InfrastructureType	string	road
ground_horsering/horsering_ground.AddProperty	layers	mgLayers	16777215
ground_horsering/horsering_ground.SetDisabled	0
ground_horsering/horsering_ground.SetLocalPosition	0.0000000 0.0000000 0.0000000
ground_horsering/horsering_ground.SetLocalRotation	0.0000000 0.0000000 0.0000000
#ground_horsering/horsering_ground.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
ground_horsering/horsering_ground.SetLocalScale	1.0000000 1.0000000 1.0000000
ground_horsering/horsering_ground.SetCastShadows	0
ground_horsering/horsering_ground.SetRenderOrder	0.0000000
ground_horsering/horsering_ground.SetDoNotRender	0
ground_horsering/horsering_ground.SetBSPData horsering1210bis.bsp
ground_horsering/horsering_ground.SetRenderingDepth 8
ground_horsering/horsering_ground.SetAmbientOcclusionMap 
ground_horsering/horsering_ground.SetNearClippingDistance 0.0000000
ground_horsering/horsering_ground.SetFarClippingDistance 

# Object sky_bluedream with type sivicPackage
sky_bluedream.SetDisabled	0
sky_bluedream.SetLocalPosition	0.0000000 0.0000000 0.0000000
sky_bluedream.SetLocalRotation	0.0000000 0.0000000 0.0000000
#sky_bluedream.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
sky_bluedream.SetLocalScale	1.0000000 1.0000000 1.0000000
sky_bluedream.SetPackageData	Sky_bluedream.zip

# Object sky_bluedream/sky with type mgSkyBoxActor
sky_bluedream/sky.AddProperty	ColorLabel	mgColor	0 176 240 255
sky_bluedream/sky.SetDisabled	0
sky_bluedream/sky.SetLocalPosition	0.0000000 0.0000000 0.0000000
sky_bluedream/sky.SetLocalRotation	0.0000000 0.0000000 0.0000000
#sky_bluedream/sky.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
sky_bluedream/sky.SetLocalScale	1.0000000 1.0000000 1.0000000
sky_bluedream/sky.SetCastShadows	0
sky_bluedream/sky.SetRenderOrder	-1.0000000
sky_bluedream/sky.SetDoNotRender	0
sky_bluedream/sky.SetMesh skybox/bluedream

# Object sun with type sivicPackage
sun.SetDisabled	0
sun.SetLocalPosition	0.0000000 0.0000000 0.0000000
sun.SetLocalRotation	0.0000000 0.0000000 0.0000000
#sun.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
sun.SetLocalScale	1.0000000 1.0000000 1.0000000
sun.SetPackageData	Sun.zip

# Object sun/sky_ref with type mgPositionable
sun/sky_ref.SetDisabled	0
sun/sky_ref.SetLocalPosition	0.0000000 0.0000000 0.0000000
sun/sky_ref.SetLocalRotation	90.0000000 0.0000000 0.0000000
#sun/sky_ref.SetLocalRotationAngles	89.9999924 -0.0000000 0.0000000
sun/sky_ref.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object sun/sun with type mgLightSource
sun/sun.AddProperty	LightType	string	sun
sun/sun.SetDisabled	0
sun/sun.MakeChildOf sun/sky_ref
sun/sun.SetLocalPosition	0.0000000 100000.0000000 0.0000000
sun/sun.SetLocalRotation	-90.0000000 0.0000000 0.0000000
#sun/sun.SetLocalRotationAngles	-89.9999924 0.0000000 0.0000000
sun/sun.SetLocalScale	1.0000000 1.0000000 1.0000000
sun/sun.SetColor	1.0000000 1.0000000 1.0000000 1.0000000
sun/sun.SetIntensityScale	1.0000000
sun/sun.SetAttenuationFactors	1.0000000 0.0000000 0.0000000
sun/sun.SetCastShadows	1

# Object ego_car with type sivicPackage
ego_car.SetDisabled	0
ego_car.SetLocalPosition	0.0000000 0.0000000 0.0000000
ego_car.SetLocalRotation	0.0000000 0.0000000 0.0000000
#ego_car.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
ego_car.SetLocalScale	1.0000000 1.0000000 1.0000000
ego_car.SetPackageData	Mini_Cooper_dynamic.zip

# Object ego_car/chassis with type sivicMeshActor
ego_car/chassis.AddProperty	ColorLabel	mgColor	255 0 0 255
ego_car/chassis.AddProperty	VehicleModel	string	Mini_Cooper
ego_car/chassis.AddProperty	VehicleType	string	car
ego_car/chassis.AddProperty	layers	mgLayers	16777215
ego_car/chassis.SetDisabled	0
ego_car/chassis.SetLocalPosition	284.0099792 301.7500000 0.3519524
ego_car/chassis.SetLocalRotation	-0.0001512 -0.0012157 180.0000000
#ego_car/chassis.SetLocalRotationAngles	-0.0007740 0.0000962 -179.9999847
ego_car/chassis.SetLocalScale	1.0000000 1.0000000 1.0000000
ego_car/chassis.SetCastShadows	0
ego_car/chassis.SetRenderOrder	1.0000000
ego_car/chassis.SetDoNotRender	0
ego_car/chassis.SetMesh	mini_cooper_Dynamic
ego_car/chassis.SetCatchShadows	1
ego_car/chassis.SetOccludeAmbient	0
ego_car/chassis.SetCameraAligned	0
ego_car/chassis.OverrideMaterial	Body Body_Black

# Object ego_car/fl with type sivicMeshActor
ego_car/fl.AddProperty	ColorLabel	mgColor	255 0 0 255
ego_car/fl.AddProperty	layers	mgLayers	16777215
ego_car/fl.SetDisabled	0
ego_car/fl.MakeChildOf ego_car/chassis
ego_car/fl.SetLocalPosition	2.6099854 0.7500000 -0.0218004
ego_car/fl.SetLocalRotation	0.0000000 0.0000000 0.0000000
#ego_car/fl.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
ego_car/fl.SetLocalScale	1.0000000 1.0000000 1.0000000
ego_car/fl.SetCastShadows	0
ego_car/fl.SetRenderOrder	1.0000000
ego_car/fl.SetDoNotRender	0
ego_car/fl.SetMesh	mini_cooper_wheel/left_wheel
ego_car/fl.SetCatchShadows	1
ego_car/fl.SetOccludeAmbient	0
ego_car/fl.SetCameraAligned	0

# Object ego_car/fr with type sivicMeshActor
ego_car/fr.AddProperty	ColorLabel	mgColor	255 0 0 255
ego_car/fr.AddProperty	layers	mgLayers	16777215
ego_car/fr.SetDisabled	0
ego_car/fr.MakeChildOf ego_car/chassis
ego_car/fr.SetLocalPosition	2.6099854 -0.7500000 -0.0218207
ego_car/fr.SetLocalRotation	0.0000000 0.0000000 0.0000000
#ego_car/fr.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
ego_car/fr.SetLocalScale	1.0000000 1.0000000 1.0000000
ego_car/fr.SetCastShadows	0
ego_car/fr.SetRenderOrder	1.0000000
ego_car/fr.SetDoNotRender	0
ego_car/fr.SetMesh	mini_cooper_wheel/right_wheel
ego_car/fr.SetCatchShadows	1
ego_car/fr.SetOccludeAmbient	0
ego_car/fr.SetCameraAligned	0

# Object ego_car/rl with type sivicMeshActor
ego_car/rl.AddProperty	ColorLabel	mgColor	255 0 0 255
ego_car/rl.AddProperty	layers	mgLayers	16777215
ego_car/rl.SetDisabled	0
ego_car/rl.MakeChildOf ego_car/chassis
ego_car/rl.SetLocalPosition	0.0000000 0.7500000 -0.0217961
ego_car/rl.SetLocalRotation	0.0000000 0.0000000 0.0000000
#ego_car/rl.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
ego_car/rl.SetLocalScale	1.0000000 1.0000000 1.0000000
ego_car/rl.SetCastShadows	0
ego_car/rl.SetRenderOrder	1.0000000
ego_car/rl.SetDoNotRender	0
ego_car/rl.SetMesh	mini_cooper_wheel/left_wheel
ego_car/rl.SetCatchShadows	1
ego_car/rl.SetOccludeAmbient	0
ego_car/rl.SetCameraAligned	0

# Object ego_car/rr with type sivicMeshActor
ego_car/rr.AddProperty	ColorLabel	mgColor	255 0 0 255
ego_car/rr.AddProperty	layers	mgLayers	16777215
ego_car/rr.SetDisabled	0
ego_car/rr.MakeChildOf ego_car/chassis
ego_car/rr.SetLocalPosition	0.0000000 -0.7500000 -0.0218164
ego_car/rr.SetLocalRotation	0.0000000 0.0000000 0.0000000
#ego_car/rr.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
ego_car/rr.SetLocalScale	1.0000000 1.0000000 1.0000000
ego_car/rr.SetCastShadows	0
ego_car/rr.SetRenderOrder	1.0000000
ego_car/rr.SetDoNotRender	0
ego_car/rr.SetMesh	mini_cooper_wheel/right_wheel
ego_car/rr.SetCatchShadows	1
ego_car/rr.SetOccludeAmbient	0
ego_car/rr.SetCameraAligned	0

# Object ego_car/CollisionModel with type sivicMeshActor
ego_car/CollisionModel.AddProperty	layers	mgLayers	16777215
ego_car/CollisionModel.SetDisabled	0
ego_car/CollisionModel.MakeChildOf ego_car/chassis
ego_car/CollisionModel.SetLocalPosition	0.0000000 0.0000000 0.0000000
ego_car/CollisionModel.SetLocalRotation	0.0000000 0.0000000 0.0000000
#ego_car/CollisionModel.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
ego_car/CollisionModel.SetLocalScale	1.0000000 1.0000000 1.0000000
ego_car/CollisionModel.SetCastShadows	0
ego_car/CollisionModel.SetRenderOrder	1.0000000
ego_car/CollisionModel.SetDoNotRender	1
ego_car/CollisionModel.SetMesh	bmw_mini_rcs/bmw_mini_rcs
ego_car/CollisionModel.SetCatchShadows	1
ego_car/CollisionModel.SetOccludeAmbient	0
ego_car/CollisionModel.SetCameraAligned	0

# Object ego_car/RCS with type sivicRCS
ego_car/RCS.SetDisabled	0
ego_car/RCS.MakeChildOf ego_car/chassis
ego_car/RCS.SetLocalPosition	1.0000000 0.0000000 0.0000000
ego_car/RCS.SetLocalRotation	0.0000000 0.0000000 0.0000000
#ego_car/RCS.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
ego_car/RCS.SetLocalScale	1.0000000 1.0000000 1.0000000
ego_car/RCS.SetCollisionModel ego_car/CollisionModel
ego_car/RCS.ClearLobes
ego_car/RCS.AddLobe 1.0000000	1.0000000	-1.0000000 0.0000000 0.0000000 0.0000000	0.0000000 -1.0000000 0.0000000 0.0000000	0.0000000 0.0000000 -1.0000000 0.0000000	0.0000000 0.0000000 0.0000000 0.0000000
ego_car/RCS.SetRCSData biw_work3_monostatic.rcs
ego_car/RCS.SetPolicy table
ego_car/RCS.SetSymetryX none
ego_car/RCS.SetSymetryY none
ego_car/RCS.SetSymetryZ none

# Object dashcam with type sivicPackage
dashcam.SetDisabled	0
dashcam.MakeChildOf ego_car/chassis
dashcam.SetLocalPosition	1.9000000 0.0000000 1.0500000
dashcam.SetLocalRotation	69.2819595 -69.2821960 -69.2818375
#dashcam.SetLocalRotationAngles	90.0001068 -0.0001964 -90.0000000
dashcam.SetLocalScale	1.0000000 1.0000000 1.0000000
dashcam.SetPackageData	generic_camera.zip

# Object dashcam/cam with type sivicCamera
dashcam/cam.SetPeriod 0.0400000
dashcam/cam.SetOMGDDSEnabled true
dashcam/cam.SetFileName cam
dashcam/cam.SetExtension .cap
dashcam/cam.On 
dashcam/cam.SetRecordEnabled false
dashcam/cam.SetExportFormat tsv
dashcam/cam.SetDisabled	0
dashcam/cam.SetLocalPosition	0.0000000 0.0000000 0.0000000
dashcam/cam.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dashcam/cam.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dashcam/cam.SetLocalScale	1.0000000 1.0000000 1.0000000
dashcam/cam.SetFrustum	-0.0041980 0.0041980 -0.0026795 0.0026795 0.0100000 10000.0000000
dashcam/cam.SetRenderSize 500 375
dashcam/cam.SetRenderer dashcam/prend
dashcam/cam.SetCaptureFileName MGEngine
dashcam/cam.SetClearColorBufferRegion 1
dashcam/cam.SetColorFormat rgb8
dashcam/cam.SetDepthFormat DEPTH_24
dashcam/cam.SetMultiSamples 4
dashcam/cam.SetCorrectDistortion 1
dashcam/cam.AddFilter dashcam/fog
dashcam/cam.AddFilter dashcam/rain
dashcam/cam.AddFilter dashcam/dof
dashcam/cam.AddFilter dashcam/distortion
dashcam/cam.AddFilter dashcam/vignetting
dashcam/cam.AddFilter dashcam/blur
dashcam/cam.AddFilter dashcam/motion
dashcam/cam.AddFilter dashcam/aperture
dashcam/cam.AddFilter dashcam/blooming
dashcam/cam.AddFilter dashcam/sensitivity
dashcam/cam.AddFilter dashcam/color
dashcam/cam.AddFilter dashcam/noise
dashcam/cam.AddFilter dashcam/ae
dashcam/cam.SetEnableIntegration 0
dashcam/cam.SetExposureTime 0.0400000
dashcam/cam.SetExposureSampling 0.0050000
dashcam/cam.SetMatrixSize 3.1334000 2.0000000
dashcam/cam.SetFocalLength 3.7320499
dashcam/cam.SetZNear 0.0100000
dashcam/cam.SetZFar 10000.0000000
dashcam/cam.SetCollectDepthImage off
dashcam/cam.SetDepthImageRange 1000
dashcam/cam.SetDepthImageResolution 1
dashcam/cam.SetImageType RGB24
dashcam/cam.SetNbEffectiveBits 8
dashcam/cam.SetRecordFormat bmp
dashcam/cam.SetPNGCompression png_1
dashcam/cam.SetModeCorrection off
dashcam/cam.SetCollectLabelImage 0
dashcam/cam.SetOccludeLabels 1

# Object dashcam/view with type sivicCameraViewport
dashcam/view.SetDisabled	0
dashcam/view.SetViewport 0 0 500 375
dashcam/view.SetCamera dashcam/cam
dashcam/view.SetColorMask 1 1 1
dashcam/view.SetMinDepthRange 0.0000000
dashcam/view.SetMaxDepthRange 100.0000000
dashcam/view.SetLookupTexture 

# Object dashcam/prend with type sivicPhysicalRenderer
dashcam/prend.SetDisabled	0
dashcam/prend.SetWireframe 0
dashcam/prend.SetNoTextures 0
dashcam/prend.SetAlphaMultisampling 1
dashcam/prend.SetClampVertexColor 0
dashcam/prend.SetClampFragmentColor 0
dashcam/prend.SetActivatedTextureChannels 3
dashcam/prend.SetEnableLighting 1
dashcam/prend.SetEnableHemisphereLighting 1
dashcam/prend.SetHemisphereDirection 0.0000000 0.0000000 1000000.0000000
dashcam/prend.SetGroundColor 1.0000000 1.0000000 1.0000000
dashcam/prend.SetSkyColor 1.0000000 1.0000000 1.0000000

# Object dashcam/fog with type sivicFogFilter
dashcam/fog.AddProperty	FoggyWeatherOnly	bool	true
dashcam/fog.SetDisabled	1
dashcam/fog.SetK 0.1000000
dashcam/fog.SetSkyLuminosity 1.0000000
dashcam/fog.SetCentroid 
dashcam/fog.SetConstantFalloff 1.0000000
dashcam/fog.SetLinearFalloff 0.0000000
dashcam/fog.SetQuadraticFalloff 0.0000000

# Object dashcam/rain with type sivicRainFilter
dashcam/rain.AddProperty	RainyWeatherOnly	bool	true
dashcam/rain.SetDisabled	1
dashcam/rain.SetTexture 
dashcam/rain.SetDispersion 1.0000000
dashcam/rain.SetThickness 1.0000000
dashcam/rain.SetNRefract 1.2000000

# Object dashcam/dof with type sivicDOFFilter
dashcam/dof.SetDisabled	1
dashcam/dof.SetFNumber 2.0000000
dashcam/dof.SetLensFocalLength 0.0100000
dashcam/dof.SetFocusDistance 1.0000000
dashcam/dof.SetMaxCoCDiameter 16.0000000
dashcam/dof.SetAutoFocus 0

# Object dashcam/distortion with type sivicDistortionFilter
dashcam/distortion.SetDisabled	1
dashcam/distortion.SetK1 0.0000000
dashcam/distortion.SetK2 0.0000000
dashcam/distortion.SetPasses 1

# Object dashcam/vignetting with type sivicSpVignettingFilter
dashcam/vignetting.SetDisabled	1
dashcam/vignetting.SetVignettingMap 

# Object dashcam/blur with type sivicGaussianBlurFilter
dashcam/blur.SetDisabled	1
dashcam/blur.SetSigma 0.0000000

# Object dashcam/motion with type sivicMotionBlurFilter
dashcam/motion.SetDisabled	1
dashcam/motion.SetOffModeBlurDuration 0.5000000

# Object dashcam/aperture with type mgToneMapFilter
dashcam/aperture.SetDisabled	1
dashcam/aperture.SetClampMin 0.0000000 0.0000000 0.0000000 1.0000000
dashcam/aperture.SetClampMax 1.0000000 1.0000000 1.0000000 1.0000000
dashcam/aperture.SetLookupTexture 

# Object dashcam/blooming with type mgGlowFilter
dashcam/blooming.SetDisabled	1
dashcam/blooming.SetResolution	256 256
dashcam/blooming.SetColorThreshold	0.1000000 0.1000000 0.1000000
dashcam/blooming.SetGamma	1.0000000
dashcam/blooming.SetBlurLevel	4
dashcam/blooming.SetBlurSpread	3.0000000
dashcam/blooming.SetBlurDirectionCount	5
dashcam/blooming.SetBlurRotation	0.0000000
dashcam/blooming.SetOriginalImageFactor	1.0000000
dashcam/blooming.SetAdditiveEffectFactor	10.0000000
dashcam/blooming.SetBrightenEffectFactor	0.0000000
dashcam/blooming.SetColorControlEnabled	0
dashcam/blooming.SetColorControlFactors	0.5000000 0.2500000 -0.2500000 -0.5000000 0.0000000
dashcam/blooming.SetBrightenSpeed	0.1000000
dashcam/blooming.SetDarkenSpeed	0.2500000

# Object dashcam/sensitivity with type mgToneMapFilter
dashcam/sensitivity.SetDisabled	1
dashcam/sensitivity.SetClampMin 0.0000000 0.0000000 0.0000000 1.0000000
dashcam/sensitivity.SetClampMax 0.0100000 0.0100000 0.0100000 1.0000000
dashcam/sensitivity.SetLookupTexture 

# Object dashcam/color with type sivicColorFilter
dashcam/color.SetDisabled	1
dashcam/color.SetColorMatrix 0.7000000 0.1500000 0.1000000 0.0000000  0.1000000 0.7000000 0.1000000 0.0000000  0.1000000 0.1000000 0.6000000 0.0000000  0.0000000 0.0000000 0.0000000 1.0000000

# Object dashcam/noise with type sivicNoiseFilter
dashcam/noise.SetDisabled	1
dashcam/noise.SetParams 0.0800000 0.0000000 0.0000000
dashcam/noise.SetType a

# Object dashcam/ae with type sivicAEFilter
dashcam/ae.SetDisabled	1
dashcam/ae.SetToneMapFilter dashcam/aperture
dashcam/ae.SetMask 
dashcam/ae.SetTargetLuminosity 0.3000000
dashcam/ae.SetProportionalGain 20.0000000
dashcam/ae.SetIntegralGain 0.0000000
dashcam/ae.SetDerivativeGain 0.1000000
dashcam/ae.SetMinMaxRatio 0.0000000
dashcam/ae.SetCurrentOutput 1.0000000
dashcam/ae.SetMinimalOutput 0.0000000
dashcam/ae.SetMaximalOutput 1000000.0000000
dashcam/ae.SetHistogramSaturationThreshold 1.0000000
dashcam/ae.SetSaturationCorrectionFactor 1.2000000
dashcam/ae.SetDarkCorrectionFactor 0.8000000
dashcam/ae.SetHistogramDarkThreshold 1.0000000

# Object radar with type sivicPackage
radar.SetDisabled	0
radar.MakeChildOf ego_car/chassis
radar.SetLocalPosition	3.2000000 0.0000000 0.0762000
radar.SetLocalRotation	0.0000000 0.0000000 0.0000000
#radar.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
radar.SetLocalScale	1.0000000 1.0000000 1.0000000
radar.SetPackageData	RadarLevel1.zip

# Object radar/em with type sivicEMChannel
radar/em.SetPeriod 0.1000000
radar/em.SetOMGDDSEnabled false
radar/em.SetFileName em
radar/em.SetExtension .cap
radar/em.On 
radar/em.SetRecordEnabled false
radar/em.SetExportFormat tsv
radar/em.SetDisabled	0
radar/em.SetEmitter radar/radar
radar/em.SetReceiver radar/radar
radar/em.SetReceiverArea 1.0000000
radar/em.SetMaxBounces 1
radar/em.SetMaxNumPaths 10
radar/em.SetWaveVelocity 299792458.0000000
radar/em.SetTransmitterAxisConvention 0
radar/em.SetReceiverAxisConvention 0

# Object radar/radar with type sivicRadar
radar/radar.SetDisabled	0
radar/radar.SetLocalPosition	0.0000000 0.0000000 0.0000000
radar/radar.SetLocalRotation	0.0000000 0.0000000 0.0000000
#radar/radar.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
radar/radar.SetLocalScale	1.0000000 1.0000000 1.0000000
radar/radar.SetCollisionModel 
radar/radar.ClearLobes
radar/radar.AddLobe 1.0000000	0.0000000	1.0000000 0.0000000 0.0000000 0.0000000	0.0000000 1.0000000 0.0000000 0.0000000	0.0000000 0.0000000 1.0000000 0.0000000	0.0000000 0.0000000 0.0000000 0.0000000
radar/radar.SetRCSData 
radar/radar.SetPolicy lobes
radar/radar.SetSymetryX none
radar/radar.SetSymetryY none
radar/radar.SetSymetryZ none
radar/radar.SetPeriod 0.1000000
radar/radar.SetOMGDDSEnabled true
radar/radar.SetFileName radar
radar/radar.SetExtension .cap
radar/radar.On 
radar/radar.SetRecordEnabled false
radar/radar.SetExportFormat tsv
radar/radar.SetPropagationChannel radar/em
radar/radar.SetAntennaType 1
radar/radar.SetModellingMode 0
radar/radar.SetComputationMode 1
radar/radar.SetDetectionMode 1
radar/radar.SetModulation 3
radar/radar.SetCarrierFrequency 76.5000000
radar/radar.SetBandWidth 300.0000000
radar/radar.SetSampleRate 40.0000000
radar/radar.SetPeriodDuration 0.0000100
radar/radar.SetChirpDuration 1.0000000
radar/radar.SetListenningDuration 0.0018000
radar/radar.SetThresholdDetection -500.0000000
radar/radar.SetAntennaMaxGain 24.0000000
radar/radar.SetAntennaStepAngle 0.5000000
radar/radar.SetAntennaOpenAngle 120.0000000
radar/radar.SetUseTracking 0
radar/radar.SetNbTargetsMax 16
radar/radar.SetFixSweepingGhostTargets 1
radar/radar.SetSweepingFixDistanceThreshold 1.0000000
radar/radar.SetSweepingFixAngleThreshold 5.0000000
radar/radar.SetSweepingFixSpeedThreshold 5.0000000

# Object radar/view with type sivicRadarViewport
radar/view.SetDisabled	0
radar/view.SetViewport 500 0 640 320
radar/view.SetRadar radar/radar
radar/view.SetViewingRange 200.0000000
radar/view.SetDisplayTargetWidth 1.0000000
radar/view.SetBackgroundColor 0.5000000 0.0000000 0.0000000 1.0000000
radar/view.SetAxisColor 0.7500000 0.7500000 0.7500000 1.0000000
radar/view.SetFontSize 12
radar/view.SetViewportOpacity 0.2500000
radar/view.SetDataColor 1.0000000 1.0000000 0.0000000 1.0000000
radar/view.SetAxisAngleStep 30.0000000
radar/view.SetAxisDistanceStep 25.0000000

# Object col_det_1 with type mgPositionable
col_det_1.SetDisabled	0
col_det_1.MakeChildOf ego_car/chassis
col_det_1.SetLocalPosition	2.9000001 -0.4000000 -0.0238000
col_det_1.SetLocalRotation	0.0001511 0.0012159 -180.0000000
#col_det_1.SetLocalRotationAngles	-0.0007741 0.0000962 179.9999847
col_det_1.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object col_det_2 with type mgPositionable
col_det_2.SetDisabled	0
col_det_2.MakeChildOf ego_car/chassis
col_det_2.SetLocalPosition	2.9000001 0.4000000 -0.3474000
col_det_2.SetLocalRotation	0.0001512 0.0012157 -180.0000000
#col_det_2.SetLocalRotationAngles	-0.0007739 0.0000963 179.9999847
col_det_2.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object col_det_3 with type mgPositionable
col_det_3.SetDisabled	0
col_det_3.MakeChildOf ego_car/chassis
col_det_3.SetLocalPosition	2.0999999 -0.4000000 -0.3474000
col_det_3.SetLocalRotation	0.0001512 0.0012157 -180.0000000
#col_det_3.SetLocalRotationAngles	-0.0007739 0.0000963 179.9999847
col_det_3.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object col_det_4 with type mgPositionable
col_det_4.SetDisabled	0
col_det_4.MakeChildOf ego_car/chassis
col_det_4.SetLocalPosition	1.3000000 -0.4000000 -0.3474000
col_det_4.SetLocalRotation	0.0001512 0.0012157 -180.0000000
#col_det_4.SetLocalRotationAngles	-0.0007739 0.0000963 179.9999847
col_det_4.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object col_det_5 with type mgPositionable
col_det_5.SetDisabled	0
col_det_5.MakeChildOf ego_car/chassis
col_det_5.SetLocalPosition	0.5000000 -0.4000000 -0.3474000
col_det_5.SetLocalRotation	0.0001512 0.0012157 -180.0000000
#col_det_5.SetLocalRotationAngles	-0.0007739 0.0000963 179.9999847
col_det_5.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object col_det_6 with type mgPositionable
col_det_6.SetDisabled	0
col_det_6.MakeChildOf ego_car/chassis
col_det_6.SetLocalPosition	-0.3000000 -0.4000000 -0.3474000
col_det_6.SetLocalRotation	0.0001512 0.0012157 -180.0000000
#col_det_6.SetLocalRotationAngles	-0.0007739 0.0000963 179.9999847
col_det_6.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object ego_car/car with type sivicCar
ego_car/car.AddProperty	ColorLabel	mgColor	255 0 0 255
ego_car/car.SetDisabled	0
ego_car/car.SetPeriod 0.0050000
ego_car/car.SetOMGDDSEnabled false
# SetCarDescriptionData will be use to load resource used to override car body color.
ego_car/car.SetCarBodyColorMaterialData body_color_material.conf
ego_car/car.SetCarBodyColor Black
# Meshes for ego_car/car: 
ego_car/car.SetChassis ego_car/chassis
ego_car/car.SetWheelFL ego_car/fl
ego_car/car.SetWheelFR ego_car/fr
ego_car/car.SetWheelRL ego_car/rl
ego_car/car.SetWheelRR ego_car/rr
ego_car/car.SetEnableWheelScale false
# Controllers for ego_car/car (analogical inputs): 
ego_car/car.SetAccCtrl car1_ThrottlePedal
ego_car/car.SetAccCtrlDuration 0.0001000
ego_car/car.SetClutchCtrl car1_ClutchPedal
ego_car/car.SetClutchCtrlDuration 0.0001000
ego_car/car.SetBrakeCtrl car1_BrakePedal
ego_car/car.SetBrakeCtrlDuration 0.0001000
ego_car/car.SetSteerCtrl car1_SteeringWheelAngle
ego_car/car.SetSteerCtrlDuration 0.0001000
# Controllers for ego_car/car (binary inputs): 
ego_car/car.SetUpGearCtrl car1_UpGear
ego_car/car.SetDownGearCtrl car1_DownGear
ego_car/car.SetUpKeyCtrl car1_UpKey
ego_car/car.SetDownKeyCtrl car1_DownKey
ego_car/car.SetStopCtrl car1_Stop
ego_car/car.SetUseAdaptativeSteeringSpeed 1
ego_car/car.SetUseRoadAsGround 1
ego_car/car.SetUseStopOnObstacles 1
ego_car/car.SetMass 1374.0000000
ego_car/car.SetWheelsSpacing 1.3000000 1.3099999 0.7500000 0.7500000
#ego_car/car.SetWheelbase 2.6099999
#ego_car/car.SetFrontTrack 1.5000000
#ego_car/car.SetRearTrack 1.5000000
ego_car/car.SetIgnitionKey 1
ego_car/car.SetGearShift 1
ego_car/car.SetAutoClutch 1
ego_car/car.SetPosition 282.6999817 301.7500000 0.6819519
ego_car/car.SetAngle -0.0007740 0.0000962 180.0000000
ego_car/car.SetGroundTireAltitude 0.0001380 0.0001380 0.0001467 0.0001467
# Shock absorbers parameters for ego_car/car: 
ego_car/car.SetShockAbsorberFL 20000.0000000 6000.0000000
ego_car/car.SetShockAbsorberFR 20000.0000000 6000.0000000
ego_car/car.SetShockAbsorberRL 20000.0000000 6000.0000000
ego_car/car.SetShockAbsorberRR 20000.0000000 6000.0000000
# Wheels parameters for ego_car/car: 
ego_car/car.SetWheelsHeight 0.0400000 0.0300000
ego_car/car.SetTireCode 225.0000000 44.4444008 18.1102009
ego_car/car.SetTireGripFR 0.9000000
ego_car/car.SetTireGripFL 0.9000000
ego_car/car.SetTireGripRR 0.9000000
ego_car/car.SetTireGripRL 0.9000000
# Masses and inertia for ego_car/car: 
ego_car/car.SetCarMasses 1500.0000000 1500.0000000 1340.0000000
ego_car/car.SetCarMomentOfInertia 305.0000000 2000.0000000 2454.0000000
ego_car/car.SetTireMass 18.0000000
ego_car/car.SetTireMomentOfInertia 1.2825000
ego_car/car.SetMaxOrderAcc 790.0000000
ego_car/car.SetMaxOrderBrk 1250.0000000
ego_car/car.SetMaxOrderSteer 0.5200000
ego_car/car.SetMaxSpeedSteer 0.7853982
ego_car/car.SetBrakeTorqueDistributionFL 0.6000000
ego_car/car.SetBrakeTorqueDistributionFR 0.6000000
ego_car/car.SetBrakeTorqueDistributionRL 0.4000000
ego_car/car.SetBrakeTorqueDistributionRR 0.4000000
# Cruise control parameters for ego_car/car: 
ego_car/car.SetCruiseControlPosition 0
ego_car/car.SetSpeedControl 0.0000000
ego_car/car.SetSpeedLimit 90.0000000
# Trajectory parameters for ego_car/car: 
ego_car/car.SetLoop 1
ego_car/car.SetCruiseControlPosition 0
ego_car/car.SetSpeedControl 0.0000000
ego_car/car.SetSpeedLimit 90.0000000
ego_car/car.SetFileNameTrajectory HorseRing
ego_car/car.SetExtensionTrajectory .trj
ego_car/car.SetFileNameTrack HorseRing
ego_car/car.SetExtensionTrack .trk
ego_car/car.SetMode 2
ego_car/car.SetSubMode 0
ego_car/car.SetPeriod 0.0050000
ego_car/car.SetOMGDDSEnabled false
ego_car/car.SetCarDescriptionCommunicationMode 0
ego_car/car.SetCarOrdersCommunicationMode 0
ego_car/car.SetCarEnvironmentCommunicationMode 0
# Car dynamic model for ego_car/car (0: Internal ; 1: External): 
ego_car/car.SetModelSelector 0
# Car dynamic model for ego_car/car, CarSim parameters (if used as External dynamic model): 
ego_car/car.SetSimfileName simfile.sim
ego_car/car.SetSimfileLocation C:\Users\Public\Documents\CarSim2016.1_Data\
ego_car/car.SetSteerAngle 0.0000000
# Initials parameters for ego_car/car: 
ego_car/car.SetInitTrajectoryIndex 5000
ego_car/car.SetInitCurrentLoop 1
ego_car/car.SetInitPosition 282.6999817 301.7500000 0.6819518
ego_car/car.SetInitAngle 0.0000000 0.0000000 180.0000000
ego_car/car.SetInitSpeed 90.0000000
ego_car/car.SetInitSpeedControl 0.0000000
ego_car/car.SetInitSpeedLimit 90.0000000
ego_car/car.SetACCSpeed 0.0000000
ego_car/car.SetPIDKp 500.0000000
ego_car/car.SetPIDKi 0.0000000
ego_car/car.SetPIDKd 0.0000000
ego_car/car.SetLateralCorrectionTimeTarget 4.0000000
ego_car/car.SetControlParameters 0.5000000 70.0000000 130.0000000 1.0000000 0.2000000

# Object dummy with type sivicPackage
dummy.SetDisabled	0
dummy.SetLocalPosition	0.0000000 0.0000000 0.0000000
dummy.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy.SetPackageData	Pedestrian.zip

# Object dummy/pedestrian with type sivicHuman
dummy/pedestrian.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian.SetDisabled	0
dummy/pedestrian.SetLocalPosition	203.8663025 310.2056885 -0.0048628
dummy/pedestrian.SetLocalRotation	0.0000000 0.0000000 -84.4032974
#dummy/pedestrian.SetLocalRotationAngles	0.0000000 0.0000000 -84.4032974
dummy/pedestrian.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian.Load	Pedestrian.def
dummy/pedestrian.SetSpeed	0.0000000
dummy/pedestrian.SetPosition 203.8663025 310.2056885 -0.0048628
dummy/pedestrian.SetAngle 0.0000000 0.0000000 -84.4032974
dummy/pedestrian.SetAccCtrl human2_Walk
dummy/pedestrian.SetSteerCtrl human2_BodyTurn
dummy/pedestrian.SetStopCtrl human2_Stop
dummy/pedestrian.SetHeadCtrl human2_HeadTurn
dummy/pedestrian.SetLoop 1
dummy/pedestrian.SetFileNameTrajectory 
dummy/pedestrian.SetExtensionTrajectory .trj
dummy/pedestrian.SetFileNameTrack 
dummy/pedestrian.SetExtensionTrack .trk
dummy/pedestrian.SetMode 0
dummy/pedestrian.SetInitTrajectoryIndex 0
dummy/pedestrian.SetInitCurrentLoop 1
dummy/pedestrian.SetInitPosition 203.8663025 310.2056885 -0.0048628
dummy/pedestrian.SetInitAngle 0.0000000 0.0000000 -84.4032974
dummy/pedestrian.SetUseRoadAsGround 1

# Object dummy/CollisionModel with type sivicMeshActor
dummy/CollisionModel.AddProperty	layers	mgLayers	16777215
dummy/CollisionModel.SetDisabled	1
dummy/CollisionModel.MakeChildOf dummy/pedestrian
dummy/CollisionModel.SetLocalPosition	0.0000000 0.0000000 0.0000000
dummy/CollisionModel.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/CollisionModel.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/CollisionModel.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/CollisionModel.SetCastShadows	0
dummy/CollisionModel.SetRenderOrder	1.0000000
dummy/CollisionModel.SetDoNotRender	0
dummy/CollisionModel.SetMesh	pedestrian_rcs/pedestrian_rcs
dummy/CollisionModel.SetCatchShadows	1
dummy/CollisionModel.SetOccludeAmbient	0
dummy/CollisionModel.SetCameraAligned	0

# Object dummy/RCS with type sivicRCS
dummy/RCS.SetDisabled	0
dummy/RCS.MakeChildOf dummy/pedestrian
dummy/RCS.SetLocalPosition	0.0000000 0.0000000 0.0000000
dummy/RCS.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/RCS.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/RCS.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/RCS.SetCollisionModel 
dummy/RCS.ClearLobes
dummy/RCS.AddLobe 1.0000000	1.0000000	-1.0000000 0.0000000 0.0000000 0.0000000	0.0000000 -1.0000000 0.0000000 0.0000000	0.0000000 0.0000000 -1.0000000 0.0000000	0.0000000 0.0000000 0.0000000 0.0000000
dummy/RCS.SetRCSData 
dummy/RCS.SetPolicy lobes
dummy/RCS.SetSymetryX none
dummy/RCS.SetSymetryY none
dummy/RCS.SetSymetryZ none

# Object dummy/pedestrian/root with type mgPositionable
dummy/pedestrian/root.SetDisabled	0
dummy/pedestrian/root.SetLocalPosition	0.0000000 0.0000000 0.5940000
dummy/pedestrian/root.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/root.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/root.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/hipsmain-joint with type mgPositionable
dummy/pedestrian/hipsmain-joint.SetDisabled	0
dummy/pedestrian/hipsmain-joint.MakeChildOf dummy/pedestrian/root
dummy/pedestrian/hipsmain-joint.SetLocalPosition	0.0000000 0.0000000 0.5940000
dummy/pedestrian/hipsmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/hipsmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/hipsmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/hipsmain with type mgMeshActor
dummy/pedestrian/hipsmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/hipsmain.SetDisabled	0
dummy/pedestrian/hipsmain.MakeChildOf dummy/pedestrian/hipsmain-joint
dummy/pedestrian/hipsmain.SetLocalPosition	0.0000000 0.0000000 -1.1880000
dummy/pedestrian/hipsmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/hipsmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/hipsmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/hipsmain.SetCastShadows	0
dummy/pedestrian/hipsmain.SetRenderOrder	1.0000000
dummy/pedestrian/hipsmain.SetDoNotRender	0
dummy/pedestrian/hipsmain.SetMesh	pedestrian/hipsmain
dummy/pedestrian/hipsmain.SetCatchShadows	1
dummy/pedestrian/hipsmain.SetOccludeAmbient	0
dummy/pedestrian/hipsmain.SetCameraAligned	0
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/hipsmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/right_upper_legmain-joint with type mgPositionable
dummy/pedestrian/right_upper_legmain-joint.SetDisabled	0
dummy/pedestrian/right_upper_legmain-joint.MakeChildOf dummy/pedestrian/hipsmain-joint
dummy/pedestrian/right_upper_legmain-joint.SetLocalPosition	0.0000000 -0.0720000 -0.2700000
dummy/pedestrian/right_upper_legmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/right_upper_legmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/right_upper_legmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/right_upper_legmain with type mgMeshActor
dummy/pedestrian/right_upper_legmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/right_upper_legmain.SetDisabled	0
dummy/pedestrian/right_upper_legmain.MakeChildOf dummy/pedestrian/right_upper_legmain-joint
dummy/pedestrian/right_upper_legmain.SetLocalPosition	0.0000000 0.0720000 -0.9180000
dummy/pedestrian/right_upper_legmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/right_upper_legmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/right_upper_legmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/right_upper_legmain.SetCastShadows	0
dummy/pedestrian/right_upper_legmain.SetRenderOrder	1.0000000
dummy/pedestrian/right_upper_legmain.SetDoNotRender	0
dummy/pedestrian/right_upper_legmain.SetMesh	pedestrian/right_upper_legmain
dummy/pedestrian/right_upper_legmain.SetCatchShadows	1
dummy/pedestrian/right_upper_legmain.SetOccludeAmbient	0
dummy/pedestrian/right_upper_legmain.SetCameraAligned	0
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/right_upper_legmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/right_lower_legmain-joint with type mgPositionable
dummy/pedestrian/right_lower_legmain-joint.SetDisabled	0
dummy/pedestrian/right_lower_legmain-joint.MakeChildOf dummy/pedestrian/right_upper_legmain-joint
dummy/pedestrian/right_lower_legmain-joint.SetLocalPosition	0.0000000 0.0000000 -0.4320000
dummy/pedestrian/right_lower_legmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/right_lower_legmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/right_lower_legmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/right_lower_legmain with type mgMeshActor
dummy/pedestrian/right_lower_legmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/right_lower_legmain.SetDisabled	0
dummy/pedestrian/right_lower_legmain.MakeChildOf dummy/pedestrian/right_lower_legmain-joint
dummy/pedestrian/right_lower_legmain.SetLocalPosition	0.0000000 0.0720000 -0.4860000
dummy/pedestrian/right_lower_legmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/right_lower_legmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/right_lower_legmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/right_lower_legmain.SetCastShadows	0
dummy/pedestrian/right_lower_legmain.SetRenderOrder	1.0000000
dummy/pedestrian/right_lower_legmain.SetDoNotRender	0
dummy/pedestrian/right_lower_legmain.SetMesh	pedestrian/right_lower_legmain
dummy/pedestrian/right_lower_legmain.SetCatchShadows	1
dummy/pedestrian/right_lower_legmain.SetOccludeAmbient	0
dummy/pedestrian/right_lower_legmain.SetCameraAligned	0
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/right_lower_legmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/right_footmain-joint with type mgPositionable
dummy/pedestrian/right_footmain-joint.SetDisabled	0
dummy/pedestrian/right_footmain-joint.MakeChildOf dummy/pedestrian/right_lower_legmain-joint
dummy/pedestrian/right_footmain-joint.SetLocalPosition	0.0000000 0.0000000 -0.4320000
dummy/pedestrian/right_footmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/right_footmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/right_footmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/right_footmain with type mgMeshActor
dummy/pedestrian/right_footmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/right_footmain.SetDisabled	0
dummy/pedestrian/right_footmain.MakeChildOf dummy/pedestrian/right_footmain-joint
dummy/pedestrian/right_footmain.SetLocalPosition	0.0000000 0.0720000 -0.0540000
dummy/pedestrian/right_footmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/right_footmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/right_footmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/right_footmain.SetCastShadows	0
dummy/pedestrian/right_footmain.SetRenderOrder	1.0000000
dummy/pedestrian/right_footmain.SetDoNotRender	0
dummy/pedestrian/right_footmain.SetMesh	pedestrian/right_footmain
dummy/pedestrian/right_footmain.SetCatchShadows	1
dummy/pedestrian/right_footmain.SetOccludeAmbient	0
dummy/pedestrian/right_footmain.SetCameraAligned	0
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/right_footmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/left_upper_legmain-joint with type mgPositionable
dummy/pedestrian/left_upper_legmain-joint.SetDisabled	0
dummy/pedestrian/left_upper_legmain-joint.MakeChildOf dummy/pedestrian/hipsmain-joint
dummy/pedestrian/left_upper_legmain-joint.SetLocalPosition	0.0000000 0.0720000 -0.2700000
dummy/pedestrian/left_upper_legmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/left_upper_legmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/left_upper_legmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/left_upper_legmain with type mgMeshActor
dummy/pedestrian/left_upper_legmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/left_upper_legmain.SetDisabled	0
dummy/pedestrian/left_upper_legmain.MakeChildOf dummy/pedestrian/left_upper_legmain-joint
dummy/pedestrian/left_upper_legmain.SetLocalPosition	0.0000000 -0.0720000 -0.9180000
dummy/pedestrian/left_upper_legmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/left_upper_legmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/left_upper_legmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/left_upper_legmain.SetCastShadows	0
dummy/pedestrian/left_upper_legmain.SetRenderOrder	1.0000000
dummy/pedestrian/left_upper_legmain.SetDoNotRender	0
dummy/pedestrian/left_upper_legmain.SetMesh	pedestrian/left_upper_legmain
dummy/pedestrian/left_upper_legmain.SetCatchShadows	1
dummy/pedestrian/left_upper_legmain.SetOccludeAmbient	0
dummy/pedestrian/left_upper_legmain.SetCameraAligned	0
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/left_upper_legmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/left_lower_legmain-joint with type mgPositionable
dummy/pedestrian/left_lower_legmain-joint.SetDisabled	0
dummy/pedestrian/left_lower_legmain-joint.MakeChildOf dummy/pedestrian/left_upper_legmain-joint
dummy/pedestrian/left_lower_legmain-joint.SetLocalPosition	0.0000000 0.0000000 -0.4320000
dummy/pedestrian/left_lower_legmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/left_lower_legmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/left_lower_legmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/left_lower_legmain with type mgMeshActor
dummy/pedestrian/left_lower_legmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/left_lower_legmain.SetDisabled	0
dummy/pedestrian/left_lower_legmain.MakeChildOf dummy/pedestrian/left_lower_legmain-joint
dummy/pedestrian/left_lower_legmain.SetLocalPosition	0.0000000 -0.0720000 -0.4860000
dummy/pedestrian/left_lower_legmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/left_lower_legmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/left_lower_legmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/left_lower_legmain.SetCastShadows	0
dummy/pedestrian/left_lower_legmain.SetRenderOrder	1.0000000
dummy/pedestrian/left_lower_legmain.SetDoNotRender	0
dummy/pedestrian/left_lower_legmain.SetMesh	pedestrian/left_lower_legmain
dummy/pedestrian/left_lower_legmain.SetCatchShadows	1
dummy/pedestrian/left_lower_legmain.SetOccludeAmbient	0
dummy/pedestrian/left_lower_legmain.SetCameraAligned	0
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/left_lower_legmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/left_footmain-joint with type mgPositionable
dummy/pedestrian/left_footmain-joint.SetDisabled	0
dummy/pedestrian/left_footmain-joint.MakeChildOf dummy/pedestrian/left_lower_legmain-joint
dummy/pedestrian/left_footmain-joint.SetLocalPosition	0.0000000 0.0000000 -0.4320000
dummy/pedestrian/left_footmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/left_footmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/left_footmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/left_footmain with type mgMeshActor
dummy/pedestrian/left_footmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/left_footmain.SetDisabled	0
dummy/pedestrian/left_footmain.MakeChildOf dummy/pedestrian/left_footmain-joint
dummy/pedestrian/left_footmain.SetLocalPosition	0.0000000 -0.0720000 -0.0540000
dummy/pedestrian/left_footmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/left_footmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/left_footmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/left_footmain.SetCastShadows	0
dummy/pedestrian/left_footmain.SetRenderOrder	1.0000000
dummy/pedestrian/left_footmain.SetDoNotRender	0
dummy/pedestrian/left_footmain.SetMesh	pedestrian/left_footmain
dummy/pedestrian/left_footmain.SetCatchShadows	1
dummy/pedestrian/left_footmain.SetOccludeAmbient	0
dummy/pedestrian/left_footmain.SetCameraAligned	0
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/left_footmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/lower_torsomain-joint with type mgPositionable
dummy/pedestrian/lower_torsomain-joint.SetDisabled	0
dummy/pedestrian/lower_torsomain-joint.MakeChildOf dummy/pedestrian/hipsmain-joint
dummy/pedestrian/lower_torsomain-joint.SetLocalPosition	0.0000000 0.0000000 0.0000000
dummy/pedestrian/lower_torsomain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/lower_torsomain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/lower_torsomain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/lower_torsomain with type mgMeshActor
dummy/pedestrian/lower_torsomain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/lower_torsomain.SetDisabled	0
dummy/pedestrian/lower_torsomain.MakeChildOf dummy/pedestrian/lower_torsomain-joint
dummy/pedestrian/lower_torsomain.SetLocalPosition	0.0000000 0.0000000 -1.1880000
dummy/pedestrian/lower_torsomain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/lower_torsomain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/lower_torsomain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/lower_torsomain.SetCastShadows	0
dummy/pedestrian/lower_torsomain.SetRenderOrder	1.0000000
dummy/pedestrian/lower_torsomain.SetDoNotRender	0
dummy/pedestrian/lower_torsomain.SetMesh	pedestrian/lower_torsomain
dummy/pedestrian/lower_torsomain.SetCatchShadows	1
dummy/pedestrian/lower_torsomain.SetOccludeAmbient	0
dummy/pedestrian/lower_torsomain.SetCameraAligned	0
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/lower_torsomain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/upper_torsomain-joint with type mgPositionable
dummy/pedestrian/upper_torsomain-joint.SetDisabled	0
dummy/pedestrian/upper_torsomain-joint.MakeChildOf dummy/pedestrian/lower_torsomain-joint
dummy/pedestrian/upper_torsomain-joint.SetLocalPosition	0.0000000 0.0000000 0.0000000
dummy/pedestrian/upper_torsomain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/upper_torsomain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/upper_torsomain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/upper_torsomain with type mgMeshActor
dummy/pedestrian/upper_torsomain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/upper_torsomain.SetDisabled	0
dummy/pedestrian/upper_torsomain.MakeChildOf dummy/pedestrian/upper_torsomain-joint
dummy/pedestrian/upper_torsomain.SetLocalPosition	0.0000000 0.0000000 -1.1880000
dummy/pedestrian/upper_torsomain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/upper_torsomain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/upper_torsomain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/upper_torsomain.SetCastShadows	0
dummy/pedestrian/upper_torsomain.SetRenderOrder	1.0000000
dummy/pedestrian/upper_torsomain.SetDoNotRender	0
dummy/pedestrian/upper_torsomain.SetMesh	pedestrian/upper_torsomain
dummy/pedestrian/upper_torsomain.SetCatchShadows	1
dummy/pedestrian/upper_torsomain.SetOccludeAmbient	0
dummy/pedestrian/upper_torsomain.SetCameraAligned	0
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/upper_torsomain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/neckmain-joint with type mgPositionable
dummy/pedestrian/neckmain-joint.SetDisabled	0
dummy/pedestrian/neckmain-joint.MakeChildOf dummy/pedestrian/upper_torsomain-joint
dummy/pedestrian/neckmain-joint.SetLocalPosition	0.0000000 0.0000000 0.3870000
dummy/pedestrian/neckmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/neckmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/neckmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/neckmain with type mgMeshActor
dummy/pedestrian/neckmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/neckmain.SetDisabled	0
dummy/pedestrian/neckmain.MakeChildOf dummy/pedestrian/neckmain-joint
dummy/pedestrian/neckmain.SetLocalPosition	0.0000000 0.0000000 -1.5749999
dummy/pedestrian/neckmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/neckmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/neckmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/neckmain.SetCastShadows	0
dummy/pedestrian/neckmain.SetRenderOrder	1.0000000
dummy/pedestrian/neckmain.SetDoNotRender	0
dummy/pedestrian/neckmain.SetMesh	pedestrian/neckmain
dummy/pedestrian/neckmain.SetCatchShadows	1
dummy/pedestrian/neckmain.SetOccludeAmbient	0
dummy/pedestrian/neckmain.SetCameraAligned	0
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/neckmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/headmain-joint with type mgPositionable
dummy/pedestrian/headmain-joint.SetDisabled	0
dummy/pedestrian/headmain-joint.MakeChildOf dummy/pedestrian/neckmain-joint
dummy/pedestrian/headmain-joint.SetLocalPosition	0.0000000 0.0000000 0.0000000
dummy/pedestrian/headmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/headmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/headmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/headmain with type mgMeshActor
dummy/pedestrian/headmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/headmain.SetDisabled	0
dummy/pedestrian/headmain.MakeChildOf dummy/pedestrian/headmain-joint
dummy/pedestrian/headmain.SetLocalPosition	0.0000000 0.0000000 -1.5749999
dummy/pedestrian/headmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/headmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/headmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/headmain.SetCastShadows	1
dummy/pedestrian/headmain.SetRenderOrder	1.0000000
dummy/pedestrian/headmain.SetDoNotRender	0
dummy/pedestrian/headmain.SetMesh	pedestrian/headmain
dummy/pedestrian/headmain.SetCatchShadows	1
dummy/pedestrian/headmain.SetOccludeAmbient	0
dummy/pedestrian/headmain.SetCameraAligned	0
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/headmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/right_claviclemain-joint with type mgPositionable
dummy/pedestrian/right_claviclemain-joint.SetDisabled	0
dummy/pedestrian/right_claviclemain-joint.MakeChildOf dummy/pedestrian/upper_torsomain-joint
dummy/pedestrian/right_claviclemain-joint.SetLocalPosition	0.0000000 -0.2700000 0.2700000
dummy/pedestrian/right_claviclemain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/right_claviclemain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/right_claviclemain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/right_claviclemain with type mgMeshActor
dummy/pedestrian/right_claviclemain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/right_claviclemain.SetDisabled	0
dummy/pedestrian/right_claviclemain.MakeChildOf dummy/pedestrian/right_claviclemain-joint
dummy/pedestrian/right_claviclemain.SetLocalPosition	0.0000000 0.1800000 0.0000000
dummy/pedestrian/right_claviclemain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/right_claviclemain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/right_claviclemain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/right_claviclemain.SetCastShadows	0
dummy/pedestrian/right_claviclemain.SetRenderOrder	1.0000000
dummy/pedestrian/right_claviclemain.SetDoNotRender	0
dummy/pedestrian/right_claviclemain.SetMesh	pedestrian/right_claviclemain
dummy/pedestrian/right_claviclemain.SetCatchShadows	1
dummy/pedestrian/right_claviclemain.SetOccludeAmbient	0
dummy/pedestrian/right_claviclemain.SetCameraAligned	0
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/right_claviclemain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/right_upper_armmain-joint with type mgPositionable
dummy/pedestrian/right_upper_armmain-joint.SetDisabled	0
dummy/pedestrian/right_upper_armmain-joint.MakeChildOf dummy/pedestrian/right_claviclemain-joint
dummy/pedestrian/right_upper_armmain-joint.SetLocalPosition	0.0000000 0.0000000 0.0000000
dummy/pedestrian/right_upper_armmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/right_upper_armmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/right_upper_armmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/right_upper_armmain with type mgMeshActor
dummy/pedestrian/right_upper_armmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/right_upper_armmain.SetDisabled	0
dummy/pedestrian/right_upper_armmain.MakeChildOf dummy/pedestrian/right_upper_armmain-joint
dummy/pedestrian/right_upper_armmain.SetLocalPosition	0.0000000 0.2700000 -1.4579999
dummy/pedestrian/right_upper_armmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/right_upper_armmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/right_upper_armmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/right_upper_armmain.SetCastShadows	0
dummy/pedestrian/right_upper_armmain.SetRenderOrder	1.0000000
dummy/pedestrian/right_upper_armmain.SetDoNotRender	0
dummy/pedestrian/right_upper_armmain.SetMesh	pedestrian/right_upper_armmain
dummy/pedestrian/right_upper_armmain.SetCatchShadows	1
dummy/pedestrian/right_upper_armmain.SetOccludeAmbient	0
dummy/pedestrian/right_upper_armmain.SetCameraAligned	0
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/right_upper_armmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/right_lower_armmain-joint with type mgPositionable
dummy/pedestrian/right_lower_armmain-joint.SetDisabled	0
dummy/pedestrian/right_lower_armmain-joint.MakeChildOf dummy/pedestrian/right_upper_armmain-joint
dummy/pedestrian/right_lower_armmain-joint.SetLocalPosition	0.0000000 0.0000000 -0.3240000
dummy/pedestrian/right_lower_armmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/right_lower_armmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/right_lower_armmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/right_lower_armmain with type mgMeshActor
dummy/pedestrian/right_lower_armmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/right_lower_armmain.SetDisabled	0
dummy/pedestrian/right_lower_armmain.MakeChildOf dummy/pedestrian/right_lower_armmain-joint
dummy/pedestrian/right_lower_armmain.SetLocalPosition	0.0000000 0.2700000 -1.1339999
dummy/pedestrian/right_lower_armmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/right_lower_armmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/right_lower_armmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/right_lower_armmain.SetCastShadows	0
dummy/pedestrian/right_lower_armmain.SetRenderOrder	1.0000000
dummy/pedestrian/right_lower_armmain.SetDoNotRender	0
dummy/pedestrian/right_lower_armmain.SetMesh	pedestrian/right_lower_armmain
dummy/pedestrian/right_lower_armmain.SetCatchShadows	1
dummy/pedestrian/right_lower_armmain.SetOccludeAmbient	0
dummy/pedestrian/right_lower_armmain.SetCameraAligned	0
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/right_lower_armmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/right_handmain-joint with type mgPositionable
dummy/pedestrian/right_handmain-joint.SetDisabled	0
dummy/pedestrian/right_handmain-joint.MakeChildOf dummy/pedestrian/right_lower_armmain-joint
dummy/pedestrian/right_handmain-joint.SetLocalPosition	0.0000000 0.0000000 -0.2700000
dummy/pedestrian/right_handmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/right_handmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/right_handmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/right_handmain with type mgMeshActor
dummy/pedestrian/right_handmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/right_handmain.SetDisabled	0
dummy/pedestrian/right_handmain.MakeChildOf dummy/pedestrian/right_handmain-joint
dummy/pedestrian/right_handmain.SetLocalPosition	0.0000000 0.2700000 -0.8640000
dummy/pedestrian/right_handmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/right_handmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/right_handmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/right_handmain.SetCastShadows	0
dummy/pedestrian/right_handmain.SetRenderOrder	1.0000000
dummy/pedestrian/right_handmain.SetDoNotRender	0
dummy/pedestrian/right_handmain.SetMesh	pedestrian/right_handmain
dummy/pedestrian/right_handmain.SetCatchShadows	1
dummy/pedestrian/right_handmain.SetOccludeAmbient	0
dummy/pedestrian/right_handmain.SetCameraAligned	0
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/right_handmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/left_claviclemain-joint with type mgPositionable
dummy/pedestrian/left_claviclemain-joint.SetDisabled	0
dummy/pedestrian/left_claviclemain-joint.MakeChildOf dummy/pedestrian/upper_torsomain-joint
dummy/pedestrian/left_claviclemain-joint.SetLocalPosition	0.0000000 0.2700000 0.2700000
dummy/pedestrian/left_claviclemain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/left_claviclemain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/left_claviclemain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/left_claviclemain with type mgMeshActor
dummy/pedestrian/left_claviclemain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/left_claviclemain.SetDisabled	0
dummy/pedestrian/left_claviclemain.MakeChildOf dummy/pedestrian/left_claviclemain-joint
dummy/pedestrian/left_claviclemain.SetLocalPosition	0.0000000 -0.1800000 0.0000000
dummy/pedestrian/left_claviclemain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/left_claviclemain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/left_claviclemain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/left_claviclemain.SetCastShadows	0
dummy/pedestrian/left_claviclemain.SetRenderOrder	1.0000000
dummy/pedestrian/left_claviclemain.SetDoNotRender	0
dummy/pedestrian/left_claviclemain.SetMesh	pedestrian/left_claviclemain
dummy/pedestrian/left_claviclemain.SetCatchShadows	1
dummy/pedestrian/left_claviclemain.SetOccludeAmbient	0
dummy/pedestrian/left_claviclemain.SetCameraAligned	0
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/left_claviclemain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/left_upper_armmain-joint with type mgPositionable
dummy/pedestrian/left_upper_armmain-joint.SetDisabled	0
dummy/pedestrian/left_upper_armmain-joint.MakeChildOf dummy/pedestrian/left_claviclemain-joint
dummy/pedestrian/left_upper_armmain-joint.SetLocalPosition	0.0000000 0.0000000 0.0000000
dummy/pedestrian/left_upper_armmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/left_upper_armmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/left_upper_armmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/left_upper_armmain with type mgMeshActor
dummy/pedestrian/left_upper_armmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/left_upper_armmain.SetDisabled	0
dummy/pedestrian/left_upper_armmain.MakeChildOf dummy/pedestrian/left_upper_armmain-joint
dummy/pedestrian/left_upper_armmain.SetLocalPosition	0.0000000 -0.2700000 -1.4579999
dummy/pedestrian/left_upper_armmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/left_upper_armmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/left_upper_armmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/left_upper_armmain.SetCastShadows	1
dummy/pedestrian/left_upper_armmain.SetRenderOrder	1.0000000
dummy/pedestrian/left_upper_armmain.SetDoNotRender	0
dummy/pedestrian/left_upper_armmain.SetMesh	pedestrian/left_upper_armmain
dummy/pedestrian/left_upper_armmain.SetCatchShadows	1
dummy/pedestrian/left_upper_armmain.SetOccludeAmbient	0
dummy/pedestrian/left_upper_armmain.SetCameraAligned	0
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/left_upper_armmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/left_lower_armmain-joint with type mgPositionable
dummy/pedestrian/left_lower_armmain-joint.SetDisabled	0
dummy/pedestrian/left_lower_armmain-joint.MakeChildOf dummy/pedestrian/left_upper_armmain-joint
dummy/pedestrian/left_lower_armmain-joint.SetLocalPosition	0.0000000 0.0000000 -0.3240000
dummy/pedestrian/left_lower_armmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/left_lower_armmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/left_lower_armmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/left_lower_armmain with type mgMeshActor
dummy/pedestrian/left_lower_armmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/left_lower_armmain.SetDisabled	0
dummy/pedestrian/left_lower_armmain.MakeChildOf dummy/pedestrian/left_lower_armmain-joint
dummy/pedestrian/left_lower_armmain.SetLocalPosition	0.0000000 -0.2700000 -1.1339999
dummy/pedestrian/left_lower_armmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/left_lower_armmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/left_lower_armmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/left_lower_armmain.SetCastShadows	1
dummy/pedestrian/left_lower_armmain.SetRenderOrder	1.0000000
dummy/pedestrian/left_lower_armmain.SetDoNotRender	0
dummy/pedestrian/left_lower_armmain.SetMesh	pedestrian/left_lower_armmain
dummy/pedestrian/left_lower_armmain.SetCatchShadows	1
dummy/pedestrian/left_lower_armmain.SetOccludeAmbient	0
dummy/pedestrian/left_lower_armmain.SetCameraAligned	0
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/left_lower_armmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object dummy/pedestrian/left_handmain-joint with type mgPositionable
dummy/pedestrian/left_handmain-joint.SetDisabled	0
dummy/pedestrian/left_handmain-joint.MakeChildOf dummy/pedestrian/left_lower_armmain-joint
dummy/pedestrian/left_handmain-joint.SetLocalPosition	0.0000000 0.0000000 -0.2700000
dummy/pedestrian/left_handmain-joint.SetLocalRotation	0.0000000 0.0000000 0.0000000
#dummy/pedestrian/left_handmain-joint.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
dummy/pedestrian/left_handmain-joint.SetLocalScale	1.0000000 1.0000000 1.0000000

# Object dummy/pedestrian/left_handmain with type mgMeshActor
dummy/pedestrian/left_handmain.AddProperty	ColorLabel	mgColor	255 255 0 255
dummy/pedestrian/left_handmain.SetDisabled	0
dummy/pedestrian/left_handmain.MakeChildOf dummy/pedestrian/left_handmain-joint
dummy/pedestrian/left_handmain.SetLocalPosition	0.0000000 -0.2700000 -0.8640000
dummy/pedestrian/left_handmain.SetLocalRotation	0.0000000 0.0000000 90.0000000
#dummy/pedestrian/left_handmain.SetLocalRotationAngles	0.0000000 -0.0000000 89.9999924
dummy/pedestrian/left_handmain.SetLocalScale	1.0000000 1.0000000 1.0000000
dummy/pedestrian/left_handmain.SetCastShadows	1
dummy/pedestrian/left_handmain.SetRenderOrder	1.0000000
dummy/pedestrian/left_handmain.SetDoNotRender	0
dummy/pedestrian/left_handmain.SetMesh	pedestrian/left_handmain
dummy/pedestrian/left_handmain.SetCatchShadows	1
dummy/pedestrian/left_handmain.SetOccludeAmbient	0
dummy/pedestrian/left_handmain.SetCameraAligned	0
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/right_handmain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/left_lower_armmain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/left_upper_armmain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/left_claviclemain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/left_handmain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/hipsmain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/right_upper_legmain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/right_lower_legmain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/right_footmain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/lower_torsomain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/left_lower_legmain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/left_upper_legmain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/left_footmain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/upper_torsomain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/neckmain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/headmain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/right_claviclemain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/right_upper_armmain
dummy/pedestrian/left_handmain.IgnoreShadows	dummy/pedestrian/right_lower_armmain

# Object ego_car_obs with type sivicPackage
ego_car_obs.SetDisabled	0
ego_car_obs.SetLocalPosition	0.0000000 0.0000000 0.0000000
ego_car_obs.SetLocalRotation	0.0000000 0.0000000 0.0000000
#ego_car_obs.SetLocalRotationAngles	0.0000000 -0.0000000 0.0000000
ego_car_obs.SetLocalScale	1.0000000 1.0000000 1.0000000
ego_car_obs.SetPackageData	CarObserver.zip

# Object ego_car_obs/car_obs with type sivicCarObserver
ego_car_obs/car_obs.SetPeriod 0.0400000
ego_car_obs/car_obs.SetOMGDDSEnabled true
ego_car_obs/car_obs.SetFileName car_obs
ego_car_obs/car_obs.SetExtension .cap
ego_car_obs/car_obs.On 
ego_car_obs/car_obs.SetRecordEnabled false
ego_car_obs/car_obs.SetExportFormat tsv
ego_car_obs/car_obs.SetDisabled	0
ego_car_obs/car_obs.SetPrecision 2
ego_car_obs/car_obs.SetObject ego_car/car

# Object ego_car_obs/view with type sivicObserverViewport
ego_car_obs/view.SetDisabled	0
ego_car_obs/view.SetViewport 0 0 400 200
# Backgound color for ego_car_obs/view: 
ego_car_obs/view.SetTransparency true
ego_car_obs/view.SetWatermark 0.1000000
ego_car_obs/view.SetBackgroundColor 1.0000000 0.0000000 0.0000000 0.1000000
# SetTopViewMode is used to select mode: "SetTopView" or "GraphView": 
ego_car_obs/view.SetTopViewMode 0
ego_car_obs/view.SetTextColor 1.0000000 1.0000000 1.0000000 1.0000000
# GraphView parameters: 
ego_car_obs/view.SetDisplay 30
ego_car_obs/view.SetModeStrip 1
ego_car_obs/view.SetGraphColor 1.0000000 1.0000000 0.0000000 0.7000000
ego_car_obs/view.SetAxisColor 1.0000000 0.0000000 0.0000000 0.7000000
ego_car_obs/view.SetTimeScale 20.0000000
ego_car_obs/view.SetYAxisScale 10.0000000
# TopView parameters: 
ego_car_obs/view.SetDispForceValue 0

# Object ped_obs with type sivicObjectObserver
ped_obs.SetPeriod 0.0400000
ped_obs.SetOMGDDSEnabled true
ped_obs.SetFileName ped_obs
ped_obs.SetExtension .cap
ped_obs.On 
ped_obs.SetRecordEnabled false
ped_obs.SetExportFormat tsv
ped_obs.SetDisabled	0
ped_obs.SetPrecision 2
ped_obs.SetObject dummy/pedestrian

# Object col_event_1 with type sivicEvent
col_event_1.SetPeriod 0.0400000
col_event_1.SetOMGDDSEnabled true
col_event_1.SetFileName col_event_1
col_event_1.SetExtension .cap
col_event_1.On 
col_event_1.SetRecordEnabled false
col_event_1.SetExportFormat tsv
col_event_1.SetDisabled	0
col_event_1.SetPrecision 2
col_event_1.SetEventFile 
col_event_1.SetIterationNbr 1
# Event parameters for "TYPE_TIME_TRJ" mode:
# col_event_1.SetEvent col_det_1 time 0.0000000
col_event_1.SetObject col_det_1
col_event_1.SetTimeEvent 0.0000000
# Event parameters for "TYPE_TIMESIVIC" mode:
# col_event_1.SetEvent col_det_1 timesivic 0.0000000
col_event_1.SetObject col_det_1
col_event_1.SetTimePeriodEvent 0.0000000
# Event parameters for "TYPE_INDEX_TRJ" mode:
# col_event_1.SetEvent col_det_1 indice 0
col_event_1.SetObject col_det_1
col_event_1.SetEventIndex 0
# Event parameters for "TYPE_POSITION" mode:
# col_event_1.SetEvent col_det_1 position 0.0000000 0.0000000 0.0000000
col_event_1.SetObject col_det_1
col_event_1.SetPositionEvent 0.0000000 0.0000000 0.0000000
col_event_1.SetDistanceToPoint 1.0000000
# Event parameters for "TYPE_DISTANCE" mode:
# col_event_1.SetEvent col_det_1 distance dummy/pedestrian
col_event_1.SetObject col_det_1
col_event_1.SetTargetObject dummy/pedestrian
col_event_1.SetDistanceToObject 0.8000000
# Event parameters for "TYPE_DDSLESS" and "TYPE_DDSGREATER" mode:
col_event_1.SetShareName localhost:4242/
# event types ddsless and ddsgreater not supported at export.
col_event_1.SetThresholdValue 1.0000000
# Event parameters for "TYPE_COMP_VALUE" mode:
col_event_1.SetEvent col_det_1 compvalue dummy/pedestrian 0.0000000 EQUAL
# Event parameters for "TYPE_COMP_PROP" mode:
col_event_1.SetEvent col_det_1 compprop dummy/pedestrian dummy/pedestrian EQUAL EQUAL
# Recording event type:
# TYPE_TIME_TRJ = 1, TYPE_TIMESIVIC = 2, TYPE_INDEX_TRJ = 3, TYPE_POSITION = 4, TYPE_DISTANCE = 5, TYPE_COMP_VALUE = 6, TYPE_COMP_PROP = 7, TYPE_DDSLESS = 20, TYPE_DDSGREATER = 21
col_event_1.SetTypeEvent 5

# Object col_event_2 with type sivicEvent
col_event_2.SetPeriod 0.0400000
col_event_2.SetOMGDDSEnabled true
col_event_2.SetFileName col_event_2
col_event_2.SetExtension .cap
col_event_2.On 
col_event_2.SetRecordEnabled false
col_event_2.SetExportFormat tsv
col_event_2.SetDisabled	0
col_event_2.SetPrecision 2
col_event_2.SetEventFile 
col_event_2.SetIterationNbr 1
# Event parameters for "TYPE_TIME_TRJ" mode:
# col_event_2.SetEvent col_det_2 time 0.0000000
col_event_2.SetObject col_det_2
col_event_2.SetTimeEvent 0.0000000
# Event parameters for "TYPE_TIMESIVIC" mode:
# col_event_2.SetEvent col_det_2 timesivic 0.0000000
col_event_2.SetObject col_det_2
col_event_2.SetTimePeriodEvent 0.0000000
# Event parameters for "TYPE_INDEX_TRJ" mode:
# col_event_2.SetEvent col_det_2 indice 0
col_event_2.SetObject col_det_2
col_event_2.SetEventIndex 0
# Event parameters for "TYPE_POSITION" mode:
# col_event_2.SetEvent col_det_2 position 0.0000000 0.0000000 0.0000000
col_event_2.SetObject col_det_2
col_event_2.SetPositionEvent 0.0000000 0.0000000 0.0000000
col_event_2.SetDistanceToPoint 1.0000000
# Event parameters for "TYPE_DISTANCE" mode:
# col_event_2.SetEvent col_det_2 distance dummy/pedestrian
col_event_2.SetObject col_det_2
col_event_2.SetTargetObject dummy/pedestrian
col_event_2.SetDistanceToObject 0.8000000
# Event parameters for "TYPE_DDSLESS" and "TYPE_DDSGREATER" mode:
col_event_2.SetShareName localhost:4242/
# event types ddsless and ddsgreater not supported at export.
col_event_2.SetThresholdValue 1.0000000
# Event parameters for "TYPE_COMP_VALUE" mode:
col_event_2.SetEvent col_det_2 compvalue dummy/pedestrian 0.0000000 EQUAL
# Event parameters for "TYPE_COMP_PROP" mode:
col_event_2.SetEvent col_det_2 compprop dummy/pedestrian dummy/pedestrian EQUAL EQUAL
# Recording event type:
# TYPE_TIME_TRJ = 1, TYPE_TIMESIVIC = 2, TYPE_INDEX_TRJ = 3, TYPE_POSITION = 4, TYPE_DISTANCE = 5, TYPE_COMP_VALUE = 6, TYPE_COMP_PROP = 7, TYPE_DDSLESS = 20, TYPE_DDSGREATER = 21
col_event_2.SetTypeEvent 5

# Object col_event_3 with type sivicEvent
col_event_3.SetPeriod 0.0400000
col_event_3.SetOMGDDSEnabled true
col_event_3.SetFileName col_event_3
col_event_3.SetExtension .cap
col_event_3.On 
col_event_3.SetRecordEnabled false
col_event_3.SetExportFormat tsv
col_event_3.SetDisabled	0
col_event_3.SetPrecision 2
col_event_3.SetEventFile 
col_event_3.SetIterationNbr 1
# Event parameters for "TYPE_TIME_TRJ" mode:
# col_event_3.SetEvent col_det_3 time 0.0000000
col_event_3.SetObject col_det_3
col_event_3.SetTimeEvent 0.0000000
# Event parameters for "TYPE_TIMESIVIC" mode:
# col_event_3.SetEvent col_det_3 timesivic 0.0000000
col_event_3.SetObject col_det_3
col_event_3.SetTimePeriodEvent 0.0000000
# Event parameters for "TYPE_INDEX_TRJ" mode:
# col_event_3.SetEvent col_det_3 indice 0
col_event_3.SetObject col_det_3
col_event_3.SetEventIndex 0
# Event parameters for "TYPE_POSITION" mode:
# col_event_3.SetEvent col_det_3 position 0.0000000 0.0000000 0.0000000
col_event_3.SetObject col_det_3
col_event_3.SetPositionEvent 0.0000000 0.0000000 0.0000000
col_event_3.SetDistanceToPoint 1.0000000
# Event parameters for "TYPE_DISTANCE" mode:
# col_event_3.SetEvent col_det_3 distance dummy/pedestrian
col_event_3.SetObject col_det_3
col_event_3.SetTargetObject dummy/pedestrian
col_event_3.SetDistanceToObject 0.8000000
# Event parameters for "TYPE_DDSLESS" and "TYPE_DDSGREATER" mode:
col_event_3.SetShareName localhost:4242/
# event types ddsless and ddsgreater not supported at export.
col_event_3.SetThresholdValue 1.0000000
# Event parameters for "TYPE_COMP_VALUE" mode:
col_event_3.SetEvent col_det_3 compvalue dummy/pedestrian 0.0000000 EQUAL
# Event parameters for "TYPE_COMP_PROP" mode:
col_event_3.SetEvent col_det_3 compprop dummy/pedestrian dummy/pedestrian EQUAL EQUAL
# Recording event type:
# TYPE_TIME_TRJ = 1, TYPE_TIMESIVIC = 2, TYPE_INDEX_TRJ = 3, TYPE_POSITION = 4, TYPE_DISTANCE = 5, TYPE_COMP_VALUE = 6, TYPE_COMP_PROP = 7, TYPE_DDSLESS = 20, TYPE_DDSGREATER = 21
col_event_3.SetTypeEvent 5

# Object col_event_4 with type sivicEvent
col_event_4.SetPeriod 0.0400000
col_event_4.SetOMGDDSEnabled true
col_event_4.SetFileName col_event_4
col_event_4.SetExtension .cap
col_event_4.On 
col_event_4.SetRecordEnabled false
col_event_4.SetExportFormat tsv
col_event_4.SetDisabled	0
col_event_4.SetPrecision 2
col_event_4.SetEventFile 
col_event_4.SetIterationNbr 1
# Event parameters for "TYPE_TIME_TRJ" mode:
# col_event_4.SetEvent col_det_4 time 0.0000000
col_event_4.SetObject col_det_4
col_event_4.SetTimeEvent 0.0000000
# Event parameters for "TYPE_TIMESIVIC" mode:
# col_event_4.SetEvent col_det_4 timesivic 0.0000000
col_event_4.SetObject col_det_4
col_event_4.SetTimePeriodEvent 0.0000000
# Event parameters for "TYPE_INDEX_TRJ" mode:
# col_event_4.SetEvent col_det_4 indice 0
col_event_4.SetObject col_det_4
col_event_4.SetEventIndex 0
# Event parameters for "TYPE_POSITION" mode:
# col_event_4.SetEvent col_det_4 position 0.0000000 0.0000000 0.0000000
col_event_4.SetObject col_det_4
col_event_4.SetPositionEvent 0.0000000 0.0000000 0.0000000
col_event_4.SetDistanceToPoint 1.0000000
# Event parameters for "TYPE_DISTANCE" mode:
# col_event_4.SetEvent col_det_4 distance dummy/pedestrian
col_event_4.SetObject col_det_4
col_event_4.SetTargetObject dummy/pedestrian
col_event_4.SetDistanceToObject 0.8000000
# Event parameters for "TYPE_DDSLESS" and "TYPE_DDSGREATER" mode:
col_event_4.SetShareName localhost:4242/
# event types ddsless and ddsgreater not supported at export.
col_event_4.SetThresholdValue 1.0000000
# Event parameters for "TYPE_COMP_VALUE" mode:
col_event_4.SetEvent col_det_4 compvalue dummy/pedestrian 0.0000000 EQUAL
# Event parameters for "TYPE_COMP_PROP" mode:
col_event_4.SetEvent col_det_4 compprop dummy/pedestrian dummy/pedestrian EQUAL EQUAL
# Recording event type:
# TYPE_TIME_TRJ = 1, TYPE_TIMESIVIC = 2, TYPE_INDEX_TRJ = 3, TYPE_POSITION = 4, TYPE_DISTANCE = 5, TYPE_COMP_VALUE = 6, TYPE_COMP_PROP = 7, TYPE_DDSLESS = 20, TYPE_DDSGREATER = 21
col_event_4.SetTypeEvent 5

# Object col_event_5 with type sivicEvent
col_event_5.SetPeriod 0.0400000
col_event_5.SetOMGDDSEnabled true
col_event_5.SetFileName col_event_5
col_event_5.SetExtension .cap
col_event_5.On 
col_event_5.SetRecordEnabled false
col_event_5.SetExportFormat tsv
col_event_5.SetDisabled	0
col_event_5.SetPrecision 2
col_event_5.SetEventFile 
col_event_5.SetIterationNbr 1
# Event parameters for "TYPE_TIME_TRJ" mode:
# col_event_5.SetEvent col_det_5 time 0.0000000
col_event_5.SetObject col_det_5
col_event_5.SetTimeEvent 0.0000000
# Event parameters for "TYPE_TIMESIVIC" mode:
# col_event_5.SetEvent col_det_5 timesivic 0.0000000
col_event_5.SetObject col_det_5
col_event_5.SetTimePeriodEvent 0.0000000
# Event parameters for "TYPE_INDEX_TRJ" mode:
# col_event_5.SetEvent col_det_5 indice 0
col_event_5.SetObject col_det_5
col_event_5.SetEventIndex 0
# Event parameters for "TYPE_POSITION" mode:
# col_event_5.SetEvent col_det_5 position 0.0000000 0.0000000 0.0000000
col_event_5.SetObject col_det_5
col_event_5.SetPositionEvent 0.0000000 0.0000000 0.0000000
col_event_5.SetDistanceToPoint 1.0000000
# Event parameters for "TYPE_DISTANCE" mode:
# col_event_5.SetEvent col_det_5 distance dummy/pedestrian
col_event_5.SetObject col_det_5
col_event_5.SetTargetObject dummy/pedestrian
col_event_5.SetDistanceToObject 0.8000000
# Event parameters for "TYPE_DDSLESS" and "TYPE_DDSGREATER" mode:
col_event_5.SetShareName localhost:4242/
# event types ddsless and ddsgreater not supported at export.
col_event_5.SetThresholdValue 1.0000000
# Event parameters for "TYPE_COMP_VALUE" mode:
col_event_5.SetEvent col_det_5 compvalue dummy/pedestrian 0.0000000 EQUAL
# Event parameters for "TYPE_COMP_PROP" mode:
col_event_5.SetEvent col_det_5 compprop dummy/pedestrian dummy/pedestrian EQUAL EQUAL
# Recording event type:
# TYPE_TIME_TRJ = 1, TYPE_TIMESIVIC = 2, TYPE_INDEX_TRJ = 3, TYPE_POSITION = 4, TYPE_DISTANCE = 5, TYPE_COMP_VALUE = 6, TYPE_COMP_PROP = 7, TYPE_DDSLESS = 20, TYPE_DDSGREATER = 21
col_event_5.SetTypeEvent 5

# Object col_event_6 with type sivicEvent
col_event_6.SetPeriod 0.0400000
col_event_6.SetOMGDDSEnabled true
col_event_6.SetFileName col_event_6
col_event_6.SetExtension .cap
col_event_6.On 
col_event_6.SetRecordEnabled false
col_event_6.SetExportFormat tsv
col_event_6.SetDisabled	0
col_event_6.SetPrecision 2
col_event_6.SetEventFile 
col_event_6.SetIterationNbr 1
# Event parameters for "TYPE_TIME_TRJ" mode:
# col_event_6.SetEvent col_det_6 time 0.0000000
col_event_6.SetObject col_det_6
col_event_6.SetTimeEvent 0.0000000
# Event parameters for "TYPE_TIMESIVIC" mode:
# col_event_6.SetEvent col_det_6 timesivic 0.0000000
col_event_6.SetObject col_det_6
col_event_6.SetTimePeriodEvent 0.0000000
# Event parameters for "TYPE_INDEX_TRJ" mode:
# col_event_6.SetEvent col_det_6 indice 0
col_event_6.SetObject col_det_6
col_event_6.SetEventIndex 0
# Event parameters for "TYPE_POSITION" mode:
# col_event_6.SetEvent col_det_6 position 0.0000000 0.0000000 0.0000000
col_event_6.SetObject col_det_6
col_event_6.SetPositionEvent 0.0000000 0.0000000 0.0000000
col_event_6.SetDistanceToPoint 1.0000000
# Event parameters for "TYPE_DISTANCE" mode:
# col_event_6.SetEvent col_det_6 distance dummy/pedestrian
col_event_6.SetObject col_det_6
col_event_6.SetTargetObject dummy/pedestrian
col_event_6.SetDistanceToObject 0.8000000
# Event parameters for "TYPE_DDSLESS" and "TYPE_DDSGREATER" mode:
col_event_6.SetShareName localhost:4242/
# event types ddsless and ddsgreater not supported at export.
col_event_6.SetThresholdValue 1.0000000
# Event parameters for "TYPE_COMP_VALUE" mode:
col_event_6.SetEvent col_det_6 compvalue dummy/pedestrian 0.0000000 EQUAL
# Event parameters for "TYPE_COMP_PROP" mode:
col_event_6.SetEvent col_det_6 compprop dummy/pedestrian dummy/pedestrian EQUAL EQUAL
# Recording event type:
# TYPE_TIME_TRJ = 1, TYPE_TIMESIVIC = 2, TYPE_INDEX_TRJ = 3, TYPE_POSITION = 4, TYPE_DISTANCE = 5, TYPE_COMP_VALUE = 6, TYPE_COMP_PROP = 7, TYPE_DDSLESS = 20, TYPE_DDSGREATER = 21
col_event_6.SetTypeEvent 5



# Viewport ordering

editor/view.ToFront
dashcam/view.ToFront
radar/view.ToFront
ego_car_obs/view.ToFront
